import { ArrowRight, ArrowUpRight, Check } from "lucide-react";
import { NoFappLogo } from "@/components/brand/no-fapp-logo";
import { Button } from "@/components/ui/button";
import { DeviceMockup } from "@/components/device/DeviceMockup";
import { mockupGroups } from "@/components/device/mockupGroups";
import { FadeUp, FloatingDevice, Parallax } from "@/components/motion/Reveal";
import { SectionHeading } from "@/components/motion/SectionHeading";
import { getRegisterUrl } from "@/lib/site";

const hero = mockupGroups.hero.screens;

export function PremiumExperience() {
  return <>
    <section className="hero relative overflow-hidden px-5 pb-20 pt-32 sm:pt-40 lg:px-8 lg:pb-28 lg:pt-44"><div className="texture-dots absolute inset-0 opacity-30" /><div className="hero-glow absolute inset-0" /><div className="mx-auto grid max-w-[1400px] items-center gap-12 lg:grid-cols-[.9fr_1.1fr] lg:gap-4"><FadeUp className="relative z-20 lg:pl-[4vw]"><p className="eyebrow">The protocol → est. today</p><h1 className="mt-5 max-w-3xl font-display text-[clamp(3.5rem,9vw,8.5rem)] uppercase leading-[.78] tracking-[-.055em]">How long can you keep your hands <span className="text-primary">off?</span></h1><p className="mt-8 max-w-lg text-base leading-relaxed text-muted sm:text-lg">A private, slightly ridiculous way to build self-control. Check in daily, climb the ranks, and never fight alone.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Button href={getRegisterUrl()} size="lg">Start your streak <ArrowRight className="ml-2 size-4" /></Button><a href="#how-it-works" className="text-sm font-bold text-muted underline decoration-border underline-offset-4 hover:text-foreground">See the protocol</a></div></FadeUp><div className="hero-devices relative mx-auto mt-4 h-[470px] w-full max-w-[720px] sm:h-[610px] lg:mt-0" aria-label="No Fapp app preview"><FadeUp delay={100} className="absolute left-[1%] top-[15%] z-10 w-[34%] sm:left-[5%] sm:w-[31%]"><FloatingDevice duration={8}><DeviceMockup {...hero[0]} priority rotate={-5} scale={.9} /></FloatingDevice></FadeUp><FadeUp delay={40} className="absolute left-1/2 top-0 z-20 w-[48%] -translate-x-1/2 sm:w-[43%]"><FloatingDevice duration={11}><DeviceMockup {...hero[0]} priority scale={1.05} /></FloatingDevice></FadeUp><FadeUp delay={160} className="absolute right-0 top-[20%] z-10 w-[34%] sm:right-[4%] sm:w-[31%]"><FloatingDevice duration={7}><DeviceMockup {...hero[1]} priority rotate={5} scale={.92} /></FloatingDevice></FadeUp><span className="spark spark-one">✦</span><span className="spark spark-two">{"///"}</span><span className="spark spark-three">✦</span></div></div></section>

    <section id="how-it-works" className="border-y border-border bg-surface px-5 py-20 sm:py-28 lg:px-8 lg:py-32"><div className="mx-auto max-w-6xl"><FadeUp><SectionHeading eyebrow="The protocol →" title={<>The rules are<br /><span className="text-primary">embarrassingly simple.</span></>}>No lectures. No shame spiral. Just one honest decision, made every day.</SectionHeading></FadeUp><ol className="mt-16 grid border-t border-border md:grid-cols-3">{[["01", "Decide once", "Set your intention. No complicated setup, no dramatic vows."], ["02", "Check in daily", "Tap the button, tell the truth, keep the streak moving."], ["03", "Climb together", "Earn ranks and let your squad bring the right kind of pressure."]].map(([n, t, d], i) => <FadeUp key={n} delay={i * 70}><li className="rule-item"><b>{n}</b><h3>{t}</h3><p>{d}</p></li></FadeUp>)}</ol></div></section>

    <section id="checkin" className="relative mx-auto grid max-w-6xl items-center gap-10 px-5 py-24 sm:py-32 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-40"><FadeUp><SectionHeading eyebrow="Daily declaration →" title={<>Did you<br /><span className="text-primary">survive today?</span></>}>One tap. One tiny moment of honesty. The streak does the rest.</SectionHeading><Button href={getRegisterUrl()} variant="ghost" className="mt-8">I survived today <Check className="ml-2 size-4" /></Button></FadeUp><div className="story-device"><span className="spark spark-checkin-1">✦</span><span className="spark spark-checkin-2">{"///"}</span><FloatingDevice duration={9}><DeviceMockup {...mockupGroups.daily.screens[0]} /></FloatingDevice></div></section>

    <section id="audit" className="relative overflow-hidden bg-surface px-5 py-24 sm:py-32 lg:px-8 lg:py-40"><div className="relative z-10 mx-auto grid max-w-6xl items-center gap-8 lg:grid-cols-[.8fr_1.2fr]"><FadeUp><SectionHeading eyebrow="The audit →" title={<>Keep the<br /><span className="text-primary">receipts.</span></>}>Your calendar knows. Your future self deserves the full report.</SectionHeading></FadeUp><div className="audit-stage relative mx-auto h-[590px] w-full max-w-[600px]"><Parallax speed="secondary" className="absolute right-[2%] top-[12%] w-[47%] opacity-45"><DeviceMockup {...mockupGroups.calendar.screens[1]} rotate={1} /></Parallax><Parallax speed="primary" className="absolute left-[12%] top-0 z-10 w-[53%]"><DeviceMockup {...mockupGroups.calendar.screens[0]} /></Parallax><span className="spark spark-audit-1">✦</span><span className="spark spark-audit-2">{"///"}</span></div></div></section>

    <section id="friends" className="mx-auto max-w-6xl overflow-hidden px-5 py-24 sm:py-32 lg:px-8 lg:py-40"><div className="grid items-center gap-12 lg:grid-cols-[.75fr_1.25fr]"><FadeUp><SectionHeading eyebrow="The boys →" title={<>Self-control is<br /><span className="text-primary">a team sport.</span></>}>Create a squad, keep each other honest, and turn your quiet little promise into very public pressure.</SectionHeading><Button href={getRegisterUrl()} className="mt-8">Create your squad <ArrowUpRight className="ml-2 size-4" /></Button></FadeUp><div className="leader-stage relative mx-auto h-[510px] w-full max-w-[680px]"><div className="absolute left-[4%] top-[10%] w-[45%] transition-transform duration-500 hover:-translate-x-3"><DeviceMockup {...mockupGroups.social.screens[0]} rotate={-1} /></div><div className="absolute right-[3%] top-[18%] w-[43%] transition-transform duration-500 hover:translate-x-3"><DeviceMockup {...mockupGroups.social.screens[1]} rotate={1} /></div><span className="spark spark-friend-1">✦</span><span className="spark spark-friend-2">{"///"}</span><span className="spark spark-friend-3">✦</span></div></div></section>

    <section id="stats" className="relative overflow-hidden bg-surface-pressed px-5 py-24 sm:py-32 lg:px-8 lg:py-40"><div className="relative z-10 mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[1fr_.9fr]"><div className="stats-type" aria-hidden="true"><span>3 days</span><span>100% discipline</span><span>0 incidents</span><span>17:18 avg</span></div><FadeUp className="relative z-10 mx-auto w-[55%] max-w-[330px]"><DeviceMockup {...mockupGroups.stats.screens[0]} /></FadeUp></div></section>

    <section id="profile" className="mx-auto grid max-w-6xl items-center gap-12 px-5 py-24 sm:py-32 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-40"><FadeUp><SectionHeading eyebrow="Personal identity →" title={<>Your profile.<br /><span className="text-primary">Your rules.</span></>}>Pick a look, pick a rank, pick the person you become after a few suspiciously productive weeks.</SectionHeading></FadeUp><div className="profile-stage relative mx-auto h-[520px] w-full max-w-[570px]"><FloatingDevice duration={10} className="absolute left-1/4 top-0 z-10 w-[52%]"><DeviceMockup {...mockupGroups.profile.screens[0]} /></FloatingDevice>{["✦", "///", "✦", "///"].map((mark, i) => <span key={i} className={`profile-mark mark-${i}`}>{mark}</span>)}</div></section>

    <section id="platforms" className="relative overflow-hidden border-y border-border bg-surface-secondary px-5 py-24 sm:py-32 lg:px-8"><div className="relative z-10 mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><FadeUp><SectionHeading eyebrow="No excuses →" title={<>Your phone is supported.<br /><span className="text-primary">Pick your weapon.</span></>}>Available on iOS and Android. Download the app, join your friends, and start your streak wherever your habits live.</SectionHeading><div className="mt-8 flex flex-wrap items-center gap-4"><a href={getRegisterUrl()} aria-label="Download on the App Store" className="inline-block transition-transform duration-200 hover:-translate-y-1 hover:opacity-95 focus-visible:outline-2 focus-visible:outline-primary"><img src="/icons/app-store-badge.svg" alt="Download on the App Store" width={160} height={48} className="h-12 w-auto shadow-md" /></a><a href={getRegisterUrl()} aria-label="Get it on Google Play" className="inline-block transition-transform duration-200 hover:-translate-y-1 hover:opacity-95 focus-visible:outline-2 focus-visible:outline-primary"><img src="/icons/google-play-badge.svg" alt="Get it on Google Play" width={160} height={48} className="h-12 w-auto shadow-md" /></a></div></FadeUp><div className="platform-stage relative mx-auto h-[460px] w-full max-w-[580px] sm:h-[500px]"><div className="absolute left-[2%] top-6 w-[46%] sm:left-[4%] sm:w-[44%]"><DeviceMockup {...mockupGroups.platforms.screens[0]} rotate={-4} scale={0.96} /></div><div className="absolute right-[2%] top-0 z-10 w-[48%] sm:right-[4%] sm:w-[46%]"><DeviceMockup {...mockupGroups.platforms.screens[1]} rotate={4} scale={1.02} /></div></div></div></section>

    <section className="final-showcase relative overflow-hidden bg-primary px-5 pb-28 pt-24 text-primary-foreground sm:pb-36 lg:px-8 lg:pb-44 lg:pt-32"><div className="mx-auto max-w-6xl text-center"><FadeUp><p className="eyebrow text-primary-foreground/70">One challenge / way too much infrastructure</p><h2 className="mt-5 font-display text-[clamp(3.3rem,8vw,8rem)] uppercase leading-[.8] tracking-[-.04em]">One challenge.<br /><span className="text-background">Way too much<br className="sm:hidden" /> infrastructure.</span></h2></FadeUp><div className="final-devices relative mx-auto mt-20 h-[400px] max-w-[1140px] sm:h-[540px] lg:h-[640px]">{mockupGroups.showcase.screens.map((screen, i) => <div key={screen.src} className={`final-device final-${i}`}><FloatingDevice duration={8 + (i % 3) * 2}><DeviceMockup {...screen} rotate={[-8, -4, 0, 4, 8][i]} scale={i === 2 ? 1.05 : 1} /></FloatingDevice></div>)}</div></div></section>

    <section className="relative overflow-hidden bg-background px-5 py-24 text-center sm:py-32 lg:px-8"><div className="auth-pattern-bg dark:hidden" style={{ backgroundImage: "url('/icons/banana-light.png')" }} aria-hidden="true" /><div className="auth-pattern-bg hidden dark:block" style={{ backgroundImage: "url('/icons/banana-dark.png')" }} aria-hidden="true" /><div className="brand-ghost" aria-hidden="true">NO F APP</div><FadeUp><SectionHeading align="center" eyebrow="Day one starts when you do →" title={<>Think you can<br /><span className="text-primary">last the month?</span></>}>Invite the boys. Start the streak. Protect your reputation.</SectionHeading><Button href={getRegisterUrl()} size="lg" className="mt-9">Start the challenge <ArrowRight className="ml-2 size-4" /></Button><p className="mt-5 text-sm text-muted">Already playing? <a href="/login" className="font-bold text-foreground underline underline-offset-4">Sign in</a></p></FadeUp></section>

    <footer className="border-t border-border bg-surface-pressed px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[1.2fr_1fr_1fr]"><div><NoFappLogo compact /><p className="mt-4 max-w-[13rem] text-sm leading-relaxed text-muted">Self-control is easy<br />Until friends watching.</p></div><div className="grid grid-cols-2 gap-8 text-sm"><div><b className="eyebrow text-foreground">Product</b><div className="mt-4 grid gap-2 text-muted"><a href="#how-it-works">How it works</a><a href="#stats">Ranks</a><a href="#friends">Leaderboard</a><a href="#friends">Friends</a></div></div><div><b className="eyebrow text-foreground">Legal</b><div className="mt-4 grid gap-2 text-muted"><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="mailto:hello@nofapp.app">Contact</a></div></div></div><div className="text-sm md:text-right"><b className="eyebrow text-foreground">Available on</b><p className="mt-4 text-muted">iOS / Android</p></div></div><div className="mx-auto mt-10 flex max-w-6xl flex-col gap-2 border-t border-border pt-5 text-xs text-muted sm:flex-row sm:justify-between"><span>© 2026 No F app</span><span>Made for friends with questionable competitive instincts</span><span>ES / EN</span></div></footer>
  </>;
}
