import { ArrowUpRight, Check } from "lucide-react";
import { AvatarVariant } from "@/components/avatars/variants";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Surface } from "@/components/ui/surface";
import { copy } from "@/content/copy";
import { getLoginUrl, getRegisterUrl } from "@/lib/site";

export function Hero() { return <section className="hero-glow relative overflow-hidden px-5 pb-20 pt-32 sm:pb-28 sm:pt-40 lg:px-8 lg:pb-36 lg:pt-48"><div className="texture-dots absolute inset-0 opacity-20" aria-hidden="true"/><div className="relative mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-16"><div className="relative z-10"><p className="mb-5 text-xs font-bold uppercase tracking-[.25em] text-primary">The self-control app</p><h1 className="max-w-3xl font-display text-[clamp(3.35rem,8vw,7.5rem)] uppercase leading-[.83] tracking-[-.04em]">{copy.hero.title}</h1><p className="mt-8 max-w-xl text-base leading-relaxed text-muted sm:text-lg">{copy.hero.subcopy}</p><div className="mt-8 flex flex-wrap items-center gap-4 sm:mt-9"><Button href={getRegisterUrl()} size="lg">{copy.nav.cta}<ArrowUpRight className="ml-2 size-4"/></Button><a href={getLoginUrl()} className="text-sm font-bold text-foreground underline decoration-border underline-offset-4 hover:text-primary">{copy.nav.signIn}</a></div><p className="mt-4 text-xs text-muted">{copy.hero.note}</p></div><div className="relative mx-auto min-h-[350px] w-full max-w-[480px] sm:min-h-[390px]" aria-hidden="true"><Surface className="absolute right-0 top-2 z-10 w-[82%] rotate-2 border-primary/30 bg-surface-raised p-5 shadow-lg sm:top-5 sm:p-6"><div className="flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-widest text-muted">Current streak</span><Badge>Active</Badge></div><strong className="mt-3 block font-display text-7xl leading-none text-foreground sm:text-8xl">00</strong><span className="text-xs uppercase tracking-widest text-muted">days</span><div className="mt-6 flex -space-x-2"><AvatarVariant id="flora" size="sm"/><AvatarVariant id="milo" size="sm"/><AvatarVariant id="felix" size="sm"/></div></Surface><Surface className="absolute bottom-1 left-0 z-20 w-[74%] -rotate-3 p-4 sm:bottom-5 sm:p-5"><p className="text-xs font-bold uppercase tracking-widest text-muted">Today&apos;s check-in</p><div className="mt-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-primary text-primary-foreground"><Check className="size-5"/></span><div><p className="font-display text-xl uppercase">Not today.</p><p className="text-xs text-muted">The streak begins here.</p></div></div></Surface><span className="absolute bottom-0 right-0 font-display text-6xl uppercase text-primary/20 sm:text-8xl">Day 01</span></div></div></section>; }
